---
- name: Validations
  ansible.builtin.include_tasks:
    file: validation.yaml

- name: Set policy package name to default if not present
  ansible.builtin.set_fact:
    _policy_pkg: "{{ policy_pkg if policy_pkg | default('', true) | trim != '' else vdom }}"

- name: Construct comment
  ansible.builtin.set_fact:
    _comment: "{{ (comment + ', ') if comment | default('', true) else '' }}Created by Ansible"

- name: Fortimanager frame
  ansible.builtin.include_tasks:
    file: fortimanager_frame.yaml
