- name: FortiManager Policy & Objects block
  block:
    - name: Locking adom
      fortinet.fortimanager.fmgr_pm_config_workspace_lock:
        workspace_locking_adom: "{{ adom }}"
        adom: "{{ adom }}"
      delegate_to: fortimanager

    - name: Create local firewall address
      fortinet.fortimanager.fmgr_firewall_address:
        adom: "{{ adom }}"
        workspace_locking_adom: "{{ adom }}" 
        state: "present"
        firewall_address:
          name: "{{ tunnel_name }}_local_{{ local_subnets_index }}"
          subnet: "{{ local_subnets_item }}"
          comment: "{{ (comment + ', ') if comment | default('', true) else '' }}Created by Ansible"
      loop: "{{ local_subnets }}"
      loop_control:
        loop_var: local_subnets_item
        index_var: local_subnets_index
      register: _local_firewall_address_result
      delegate_to: fortimanager

    - debug: var=_local_firewall_address_result

    - name: Create remote firewall address
      fortinet.fortimanager.fmgr_firewall_address:
        adom: "{{ adom }}"
        workspace_locking_adom: "{{ adom }}"
        state: "present"
        firewall_address:
          name: "{{ tunnel_name }}_remote_{{ remote_subnets_index }}"
          subnet: "{{ remote_subnets_item }}"
          comment: "{{ (comment + ', ') if comment | default('', true) else '' }}Created by Ansible"
      loop: "{{ remote_subnets }}"
      loop_control:
        loop_var: remote_subnets_item
        index_var: remote_subnets_index
      register: _remote_firewall_address_result
      delegate_to: fortimanager

    - debug: var=_remote_firewall_address_result

    - name: Create address group for local addresses
      fortinet.fortimanager.fmgr_firewall_addrgrp:
        adom: "{{ adom }}"
        workspace_locking_adom: "{{ adom }}"
        state: present

    - name: Commiting changes
      fortinet.fortimanager.fmgr_pm_config_workspace_commit:
        workspace_locking_adom: "{{ adom }}"
        adom: "{{ adom }}"
      delegate_to: fortimanager

  always:
    - name: Unlocking adom
      fortinet.fortimanager.fmgr_pm_config_workspace_unlock:
        workspace_locking_adom: "{{ adom }}"
        adom: "{{ adom }}"
      delegate_to: fortimanager